version: '3'

services:
  ghost-custom-gui:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      API_URL: ${API_URL}
    ports:
        - "3600:8080"
    networks:
      - ghost-custom-app-network

networks:
  ghost-custom-app-network:
   
