version: '3'

services:
  ghost-custom-gui:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      API_URL: ${API_URL}
    ports:
        - "3600:80"

networks:
  default:
    external:
      name: ghost-services
   
